In [1]:
# Importamos las librerías que necesitamos
import pandas as pd
import numpy as np

user = pd.read_csv('DatosUsuariosRedesSociales.csv')

user.sample(5)

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car
878,31,non-binary,6,Facebook,Sports,Australia,Urban,Marketer Manager,16906,False,True,False
370,34,female,3,Instagram,Lifestlye,United States,Rural,Software Engineer,14868,False,True,False
818,60,male,1,Instagram,Travel,United Kingdom,Sub_Urban,Student,15560,False,False,True
309,50,non-binary,7,Facebook,Sports,United Kingdom,Rural,Student,11560,True,True,False
26,39,male,2,Instagram,Lifestlye,Australia,Urban,Software Engineer,17718,True,False,False

In [5]:
user.groupby('platform').mean(numeric_only = True)

,age,time_spent,income,indebt,isHomeOwner,Owns_Car
platform,,,,,,
Facebook,40.846906,5.055375,15250.276873,0.485342,0.504886,0.524430
Instagram,40.892562,5.151515,14662.454545,0.506887,0.465565,0.523416
YouTube,41.218182,4.869697,15183.384848,0.496970,0.557576,0.569697

In [6]:
edad_media = user.groupby('platform')['age'].mean()
edad_media

platform
Facebook     40.846906
Instagram    40.892562
YouTube      41.218182
Name: age, dtype: float64

In [7]:
tiempo_uso = user.groupby('location')['time_spent'].sum().reset_index()
tiempo_uso

         location  time_spent
0       Australia        1837
1  United Kingdom        1615
2   United States        1577

In [8]:
salario_profesion = user.groupby('profession')['income'].agg(['mean','median','std','max','min']).reset_index()
salario_profesion

          profession          mean   median          std    max    min
0   Marketer Manager  14927.335211  14859.0  3015.541853  19980  10028
1  Software Engineer  14876.511905  14657.0  2976.018890  19969  10012
2            Student  15265.731392  15316.0  2866.081570  19957  10075

In [10]:
def categorizar_edad (numero):
    if 18 <= numero <= 28:
        return 'Jóven adulto'
    elif 29 <= numero <= 39:
        return 'Adulto jóven'
    elif 40 <= numero <= 50:
        return 'Mediana edad'
    else:
        return 'Adultos mayores'

In [11]:
user['age_category'] = user['age'].apply(categorizar_edad)
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category
0,56,male,3,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774,True,False,False,Adultos mayores
1,46,female,2,Facebook,Travel,United Kingdom,Urban,Student,10564,True,True,True,Mediana edad
2,32,male,8,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258,False,False,False,Adulto jóven
3,60,non-binary,5,Instagram,Travel,United Kingdom,Urban,Student,12500,False,True,False,Adultos mayores
4,25,male,1,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566,False,True,True,Jóven adulto
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536,False,True,False,Jóven adulto
996,40,non-binary,6,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711,True,False,False,Mediana edad
997,27,non-binary,5,YouTube,Travel,United Kingdom,Rural,Student,17595,True,False,True,Jóven adulto
998,61,female,4,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273,True,True,False,Adultos mayores
999,19,female,8,YouTube,Travel,Australia,Rural,Student,16284,False,True,False,Jóven adulto

In [12]:
user['income'].dtype

dtype('int64')

In [13]:
def cambiar_float(numero):
    return float(numero)

user['income'] = user['income'].apply(cambiar_float)

user['income'].dtype

dtype('float64')

In [14]:
user['time_spent'] = user['time_spent'].apply(lambda x: float(x))

user['time_spent'].dtype

dtype('float64')

In [15]:
def travel_female(col_interests,col_gender):

    if col_interests == 'Travel' and col_gender == 'female':
        return True
    else:
        return False

In [16]:
user['target_audiences']=user.apply(lambda x: travel_female(x['interests'],x['gender']),axis=1)
user

,age,gender,time_spent,platform,interests,location,demographics,profession,income,indebt,isHomeOwner,Owns_Car,age_category,target_audiences
0,56,male,3.0,Instagram,Sports,United Kingdom,Urban,Software Engineer,19774.0,True,False,False,Adultos mayores,False
1,46,female,2.0,Facebook,Travel,United Kingdom,Urban,Student,10564.0,True,True,True,Mediana edad,True
2,32,male,8.0,Instagram,Sports,Australia,Sub_Urban,Marketer Manager,13258.0,False,False,False,Adulto jóven,False
3,60,non-binary,5.0,Instagram,Travel,United Kingdom,Urban,Student,12500.0,False,True,False,Adultos mayores,False
4,25,male,1.0,Instagram,Lifestlye,Australia,Urban,Software Engineer,14566.0,False,True,True,Jóven adulto,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,22,female,8.0,Instagram,Lifestlye,United Kingdom,Rural,Marketer Manager,18536.0,False,True,False,Jóven adulto,False
996,40,non-binary,6.0,YouTube,Travel,United Kingdom,Rural,Software Engineer,12711.0,True,False,False,Mediana edad,False
997,27,non-binary,5.0,YouTube,Travel,United Kingdom,Rural,Student,17595.0,True,False,True,Jóven adulto,False
998,61,female,4.0,YouTube,Sports,Australia,Sub_Urban,Marketer Manager,16273.0,True,True,False,Adultos mayores,False
999,19,female,8.0,YouTube,Travel,Australia,Rural,Student,16284.0,False,True,False,Jóven adulto,True